[package]
name = "abilisk-firewall-server"
version = "0.1.0"
edition = "2021"

[dependencies]
native_db = { version = "0.5.3", features = ["tokio"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
